name       : zxing-cpp
version    : 2.0.0
release    : 1
source     :
    - https://github.com/zxing-cpp/zxing-cpp/archive/refs/tags/v2.0.0.tar.gz : 12b76b7005c30d34265fc20356d340da179b0b4d43d2c1b35bcca86776069f76
license    : Apache-2.0
component  : programming.library
summary    : ZXing-C++ ("zebra crossing") is an open-source, multi-format linear/matrix barcode image processing library implemented in C++.
description: |
    ZXing-C++ ("zebra crossing") is an open-source, multi-format linear/matrix barcode image processing library implemented in C++. It was originally ported from the Java ZXing Library but has been developed further and now includes many improvements in terms of quality and performance. It can both read and write barcodes in a number of formats.
builddeps  :
    - stb
setup      : |
    %patch -p1 < $pkgfiles/5142600c.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
